#include "Api.h"
#include <winhttp.h>
#include <stdexcept>
#include <vector>
std::wstring wide(const std::string&s){if(s.empty())return{};int n=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),(int)s.size(),nullptr,0);if(!n)throw std::runtime_error("Некоректний UTF-8");std::wstring o(n,L'\0');MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s.data(),(int)s.size(),o.data(),n);return o;}
std::string utf8(const std::wstring&s){if(s.empty())return{};int n=WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0,nullptr,nullptr);std::string o(n,'\0');WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),o.data(),n,nullptr,nullptr);return o;}
struct Internet{HINTERNET h;explicit Internet(HINTERNET p):h(p){if(!h)throw std::runtime_error("Не вдалося відкрити мережеве з’єднання");}~Internet(){WinHttpCloseHandle(h);}operator HINTERNET()const{return h;}Internet(const Internet&)=delete;};
J Api::call(const std::string&method,const std::string&path,const J&body){auto url=base+wide(path);URL_COMPONENTS parts{};parts.dwStructSize=sizeof(parts);parts.dwHostNameLength=parts.dwUrlPathLength=parts.dwExtraInfoLength=(DWORD)-1;if(!WinHttpCrackUrl(url.c_str(),0,0,&parts))throw std::runtime_error("Перевірте адресу сервера");std::wstring host(parts.lpszHostName,parts.dwHostNameLength),route(parts.lpszUrlPath,parts.dwUrlPathLength);if(parts.dwExtraInfoLength)route.append(parts.lpszExtraInfo,parts.dwExtraInfoLength);bool secure=parts.nScheme==INTERNET_SCHEME_HTTPS;if(!secure&&host!=L"127.0.0.1"&&host!=L"localhost"&&host!=L"::1")throw std::runtime_error("Для мережевого сервера використовуйте HTTPS");Internet session(WinHttpOpen(L"Solvia/1.1",WINHTTP_ACCESS_TYPE_DEFAULT_PROXY,nullptr,nullptr,0));WinHttpSetTimeouts(session,5000,5000,8000,8000);Internet connection(WinHttpConnect(session,host.c_str(),parts.nPort,0));Internet request(WinHttpOpenRequest(connection,wide(method).c_str(),route.c_str(),nullptr,nullptr,WINHTTP_DEFAULT_ACCEPT_TYPES,secure?WINHTTP_FLAG_SECURE:0));DWORD redirect=WINHTTP_OPTION_REDIRECT_POLICY_NEVER;WinHttpSetOption(request,WINHTTP_OPTION_REDIRECT_POLICY,&redirect,sizeof redirect);std::wstring headers=L"Content-Type: application/json\r\nAccept: application/json\r\n";if(!token.empty())headers+=L"Authorization: Bearer "+wide(token)+L"\r\n";auto data=method=="GET"?std::string{}:body.dump();if(!WinHttpSendRequest(request,headers.c_str(),(DWORD)-1,data.empty()?nullptr:data.data(),(DWORD)data.size(),(DWORD)data.size(),0)||!WinHttpReceiveResponse(request,nullptr))throw std::runtime_error("Сервер недоступний. Перевірте адресу, мережу та довіру до сертифіката.");DWORD status=0,n=sizeof status;WinHttpQueryHeaders(request,WINHTTP_QUERY_STATUS_CODE|WINHTTP_QUERY_FLAG_NUMBER,nullptr,&status,&n,nullptr);std::string response;DWORD available=0;while(WinHttpQueryDataAvailable(request,&available)&&available){if(response.size()+available>8*1024*1024)throw std::runtime_error("Відповідь сервера завелика");std::vector<char> chunk(available);DWORD read=0;if(!WinHttpReadData(request,chunk.data(),available,&read))throw std::runtime_error("З’єднання перервано. Оновіть дані перед повторенням дії.");response.append(chunk.data(),read);if(!read)break;}J j;try{j=J::parse(response);}catch(...){throw std::runtime_error("Сервер повернув некоректну відповідь");}if(status<200||status>=300)throw std::runtime_error(j.value("error","Помилка сервера"));return j;}

